In [39]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [40]:
from sklearn.preprocessing import LabelEncoder
import pickle

In [41]:
df = pd.read_csv("/content/drive/MyDrive/autos.csv", header=0, sep=',', encoding='latin1' )

In [42]:
df.head()

dateCrawled                            name  seller offerType  \
0  2016-03-24 11:52:17                      Golf_3_1.6  privat   Angebot   
1  2016-03-24 10:58:45            A5_Sportback_2.7_Tdi  privat   Angebot   
2  2016-03-14 12:52:21  Jeep_Grand_Cherokee_"Overland"  privat   Angebot   
3  2016-03-17 16:54:04              GOLF_4_1_4__3TÜRER  privat   Angebot   
4  2016-03-31 17:25:20  Skoda_Fabia_1.4_TDI_PD_Classic  privat   Angebot   

   price abtest vehicleType  yearOfRegistration    gearbox  powerPS  model  \
0    480   test         NaN                1993    manuell        0   golf   
1  18300   test       coupe                2011    manuell      190    NaN   
2   9800   test         suv                2004  automatik      163  grand   
3   1500   test  kleinwagen                2001    manuell       75   golf   
4   3600   test  kleinwagen                2008    manuell       69  fabia   

   kilometer  monthOfRegistration fuelType       brand notRepairedDamage  \
0     150000                    0   benzin  volkswagen               NaN   
1     125000                    5   diesel        audi                ja   
2     125000                    8   diesel        jeep               NaN   
3     150000                    6   benzin  volkswagen              nein   
4      90000                    7   diesel       skoda              nein   

           dateCreated  nrOfPictures  postalCode             lastSeen  
0  2016-03-24 00:00:00             0       70435  2016-04-07 03:16:57  
1  2016-03-24 00:00:00             0       66954  2016-04-07 01:46:50  
2  2016-03-14 00:00:00             0       90480  2016-04-05 12:47:46  
3  2016-03-17 00:00:00             0       91074  2016-03-17 17:40:17  
4  2016-03-31 00:00:00             0       60437  2016-04-06 10:17:21

In [43]:
#print al the differnt sellers

In [44]:
print(df.seller.value_counts())

privat        371525
gewerblich         3
Name: seller, dtype: int64


In [45]:
#remove the seller type having only 3cars

In [46]:
df[ df.seller != 'gewerblich']

dateCrawled                                          name  \
0       2016-03-24 11:52:17                                    Golf_3_1.6   
1       2016-03-24 10:58:45                          A5_Sportback_2.7_Tdi   
2       2016-03-14 12:52:21                Jeep_Grand_Cherokee_"Overland"   
3       2016-03-17 16:54:04                            GOLF_4_1_4__3TÜRER   
4       2016-03-31 17:25:20                Skoda_Fabia_1.4_TDI_PD_Classic   
...                     ...                                           ...   
371523  2016-03-14 17:48:27                    Suche_t4___vito_ab_6_sitze   
371524  2016-03-05 19:56:21         Smart_smart_leistungssteigerung_100ps   
371525  2016-03-19 18:57:12            Volkswagen_Multivan_T4_TDI_7DC_UY2   
371526  2016-03-20 19:41:08                        VW_Golf_Kombi_1_9l_TDI   
371527  2016-03-07 19:39:19  BMW_M135i_vollausgestattet_NP_52.720____Euro   

        seller offerType  price   abtest vehicleType  yearOfRegistration  \
0       privat   Angebot    480     test         NaN                1993   
1       privat   Angebot  18300     test       coupe                2011   
2       privat   Angebot   9800     test         suv                2004   
3       privat   Angebot   1500     test  kleinwagen                2001   
4       privat   Angebot   3600     test  kleinwagen                2008   
...        ...       ...    ...      ...         ...                 ...   
371523  privat   Angebot   2200     test         NaN                2005   
371524  privat   Angebot   1199     test      cabrio                2000   
371525  privat   Angebot   9200     test         bus                1996   
371526  privat   Angebot   3400     test       kombi                2002   
371527  privat   Angebot  28990  control   limousine                2013   

          gearbox  powerPS        model  kilometer  monthOfRegistration  \
0         manuell        0         golf     150000                    0   
1         manuell      190          NaN     125000                    5   
2       automatik      163        grand     125000                    8   
3         manuell       75         golf     150000                    6   
4         manuell       69        fabia      90000                    7   
...           ...      ...          ...        ...                  ...   
371523        NaN        0          NaN      20000                    1   
371524  automatik      101       fortwo     125000                    3   
371525    manuell      102  transporter     150000                    3   
371526    manuell      100         golf     150000                    6   
371527    manuell      320      m_reihe      50000                    8   

       fuelType           brand notRepairedDamage          dateCreated  \
0        benzin      volkswagen               NaN  2016-03-24 00:00:00   
1        diesel            audi                ja  2016-03-24 00:00:00   
2        diesel            jeep               NaN  2016-03-14 00:00:00   
3        benzin      volkswagen              nein  2016-03-17 00:00:00   
4        diesel           skoda              nein  2016-03-31 00:00:00   
...         ...             ...               ...                  ...   
371523      NaN  sonstige_autos               NaN  2016-03-14 00:00:00   
371524   benzin           smart              nein  2016-03-05 00:00:00   
371525   diesel      volkswagen              nein  2016-03-19 00:00:00   
371526   diesel      volkswagen               NaN  2016-03-20 00:00:00   
371527   benzin             bmw              nein  2016-03-07 00:00:00   

        nrOfPictures  postalCode             lastSeen  
0                  0       70435  2016-04-07 03:16:57  
1                  0       66954  2016-04-07 01:46:50  
2                  0       90480  2016-04-05 12:47:46  
3                  0       91074  2016-03-17 17:40:17  
4                  0       60437  2016-04-06 10:17:21  
...              ...         ...                  ..

In [47]:
#now all the seller are same so we can get rid of this column

In [48]:
df=df.drop('seller',1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  """Entry point for launching an IPython kernel.


In [49]:
#print al the different sellers

In [50]:
print(df.offerType.value_counts())

Angebot    371516
Gesuch         12
Name: offerType, dtype: int64


In [51]:
#remove the offer type having only 12 listings

In [52]:
df[df.offerType !='Gesuch']

dateCrawled                                          name  \
0       2016-03-24 11:52:17                                    Golf_3_1.6   
1       2016-03-24 10:58:45                          A5_Sportback_2.7_Tdi   
2       2016-03-14 12:52:21                Jeep_Grand_Cherokee_"Overland"   
3       2016-03-17 16:54:04                            GOLF_4_1_4__3TÜRER   
4       2016-03-31 17:25:20                Skoda_Fabia_1.4_TDI_PD_Classic   
...                     ...                                           ...   
371523  2016-03-14 17:48:27                    Suche_t4___vito_ab_6_sitze   
371524  2016-03-05 19:56:21         Smart_smart_leistungssteigerung_100ps   
371525  2016-03-19 18:57:12            Volkswagen_Multivan_T4_TDI_7DC_UY2   
371526  2016-03-20 19:41:08                        VW_Golf_Kombi_1_9l_TDI   
371527  2016-03-07 19:39:19  BMW_M135i_vollausgestattet_NP_52.720____Euro   

       offerType  price   abtest vehicleType  yearOfRegistration    gearbox  \
0        Angebot    480     test         NaN                1993    manuell   
1        Angebot  18300     test       coupe                2011    manuell   
2        Angebot   9800     test         suv                2004  automatik   
3        Angebot   1500     test  kleinwagen                2001    manuell   
4        Angebot   3600     test  kleinwagen                2008    manuell   
...          ...    ...      ...         ...                 ...        ...   
371523   Angebot   2200     test         NaN                2005        NaN   
371524   Angebot   1199     test      cabrio                2000  automatik   
371525   Angebot   9200     test         bus                1996    manuell   
371526   Angebot   3400     test       kombi                2002    manuell   
371527   Angebot  28990  control   limousine                2013    manuell   

        powerPS        model  kilometer  monthOfRegistration fuelType  \
0             0         golf     150000                    0   benzin   
1           190          NaN     125000                    5   diesel   
2           163        grand     125000                    8   diesel   
3            75         golf     150000                    6   benzin   
4            69        fabia      90000                    7   diesel   
...         ...          ...        ...                  ...      ...   
371523        0          NaN      20000                    1      NaN   
371524      101       fortwo     125000                    3   benzin   
371525      102  transporter     150000                    3   diesel   
371526      100         golf     150000                    6   diesel   
371527      320      m_reihe      50000                    8   benzin   

                 brand notRepairedDamage          dateCreated  nrOfPictures  \
0           volkswagen               NaN  2016-03-24 00:00:00             0   
1                 audi                ja  2016-03-24 00:00:00             0   
2                 jeep               NaN  2016-03-14 00:00:00             0   
3           volkswagen              nein  2016-03-17 00:00:00             0   
4                skoda              nein  2016-03-31 00:00:00             0   
...                ...               ...                  ...           ...   
371523  sonstige_autos               NaN  2016-03-14 00:00:00             0   
371524           smart              nein  2016-03-05 00:00:00             0   
371525      volkswagen              nein  2016-03-19 00:00:00             0   
371526      volkswagen               NaN  2016-03-20 00:00:00             0   
371527             bmw              nein  2016-03-07 00:00:00             0   

        postalCode             lastSeen  
0            70435  2016-04-07 03:16:57  
1            66954  2016-04-07 01:46:50  
2            90480  2016-04-05 12:47:46  
3            91074  2016-03-17 17:40:17  
4            60437  2016-04-06 10:17:21  
...            ...                  ...  
371523       39576  20

In [53]:
#now all the offers are same so we can get rid of this column

In [54]:
df=df.drop('offerType',1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  """Entry point for launching an IPython kernel.


In [55]:
#Cars having power less than 50ps and above 900ps seems a little suspicious.
#let's remove them and see what we've got now

In [56]:
print(df.shape)
df = df[(df.powerPS > 50) & (df.powerPS < 900)]
print(df.shape)


(371528, 18)
(319709, 18)


In [57]:
#around 50000 cars ahave been removed which could have introduced error to our data
#similarly, filtering our the cars having registeration years not in the mentioned ranges
#print(df.shape)

In [58]:
df = df[(df.yearOfRegistration >=1950) & (df.yearOfRegistration < 2017)]
print(df.shape)

(309171, 18)


In [59]:
#not much of a difference but still, 10000 rows have been reduced it's better to 
#get rid of faulty data instead of keeping them just to increase the size.

In [60]:
#removing irrelevant columns which are either the same for all the cars in the datset, or can 
#introduce bias, so removing them too.

In [61]:
df.drop(['name','abtest','dateCrawled','nrOfPictures','lastSeen','postalCode','dateCreated'], axis='columns',inplace=True)

In [62]:
#dropping thr duplicate from the dataframe and stroing it in a new df. here all rows having same value in all the mentioned colums will be deleted and by default
# only first occurance of anysuch row is kept
 

In [63]:
new_df = df.copy()
new_df = new_df.drop_duplicates(['price','vehicleType','yearOfRegistration','gearbox','powerPS','model','kilometer','monthOfRegistration','fuelType','notRepairedDamage'])
print(new_df)

        price vehicleType  yearOfRegistration    gearbox  powerPS  \
1       18300       coupe                2011    manuell      190   
2        9800         suv                2004  automatik      163   
3        1500  kleinwagen                2001    manuell       75   
4        3600  kleinwagen                2008    manuell       69   
5         650   limousine                1995    manuell      102   
...       ...         ...                 ...        ...      ...   
371520   3200   limousine                2004    manuell      225   
371524   1199      cabrio                2000  automatik      101   
371525   9200         bus                1996    manuell      102   
371526   3400       kombi                2002    manuell      100   
371527  28990   limousine                2013    manuell      320   

              model  kilometer  monthOfRegistration fuelType       brand  \
1               NaN     125000                    5   diesel        audi   
2             grand

In [64]:
#As the dataset contained some german words for many features, cahnging them to english 

In [65]:
new_df.gearbox.replace(('manuell', 'automatik'), ('manual', 'automatic'), inplace=True)
new_df.fuelType.replace(('benzin', 'andere', 'elektro'), ('petrol', 'others', 'electric'), inplace=True)
new_df.vehicleType.replace(('kleinwagen', 'cabrio', 'kombi', 'andere'),('small car', 'convertible', 'combination', 'others'), inplace=True)
new_df.notRepairedDamage.replace(('ja','nein'),('Yes','No'),inplace=True)

In [66]:
#### Removing the outliers
new_df = new_df[(new_df.price >= 100) & (new_df.price <= 150000)]
print(new_df)

        price  vehicleType  yearOfRegistration    gearbox  powerPS  \
1       18300        coupe                2011     manual      190   
2        9800          suv                2004  automatic      163   
3        1500    small car                2001     manual       75   
4        3600    small car                2008     manual       69   
5         650    limousine                1995     manual      102   
...       ...          ...                 ...        ...      ...   
371520   3200    limousine                2004     manual      225   
371524   1199  convertible                2000  automatic      101   
371525   9200          bus                1996     manual      102   
371526   3400  combination                2002     manual      100   
371527  28990    limousine                2013     manual      320   

              model  kilometer  monthOfRegistration fuelType       brand  \
1               NaN     125000                    5   diesel        audi   
2      

In [67]:
#Filling NaN values for columns whose data might not be there with the information provider, #which might lead to some variance but our model
#but we will still be able to give some estimate to the user
new_df['notRepairedDamage'].fillna (value='not-declared', inplace=True)
new_df['fuelType'].fillna (value='not-declared', inplace=True)
new_df['gearbox'].fillna(value='not-declared', inplace=True)
new_df['vehicleType'].fillna (value='not-declared', inplace=True)
new_df['model'].fillna (value='not-declared', inplace=True)

In [68]:
#can save the csv for future pupose.
new_df.to_csv("autos_preprocessed.csv")

In [69]:
#Columns which contain categorical values, which we'll need to convert via label encoding 
labels = ['gearbox', 'notRepairedDamage', 'model', 'brand', 'fuelType', 'vehicleType']
#looping over the labels to do the label encoding for all at once and #saving the LABEL ENCODING FILES
mapper = {}
for i in labels:
    mapper[i] = LabelEncoder()
    mapper[i].fit(new_df[i]) 
    tr = mapper[i].transform(new_df[i])
    np.save(str('classes'+i+'.npy'), mapper[i].classes_)
    print(i,":",mapper[i]) 
    new_df.loc[:, i + '_labels'] = pd.Series(tr, index=new_df.index)
    #Final data to be put in a new dataframe called "LABELED", 
labeled = new_df[['price','yearOfRegistration','powerPS' ,'kilometer','monthOfRegistration']+ [x+"_labels" for x in labels]]
print(labeled.columns)

gearbox : LabelEncoder()
notRepairedDamage : LabelEncoder()
model : LabelEncoder()
brand : LabelEncoder()
fuelType : LabelEncoder()
vehicleType : LabelEncoder()
Index(['price', 'yearOfRegistration', 'powerPS', 'kilometer',
       'monthOfRegistration', 'gearbox_labels', 'notRepairedDamage_labels',
       'model_labels', 'brand_labels', 'fuelType_labels',
       'vehicleType_labels'],
      dtype='object')


In [70]:
#Storing price in Y and rest of the data in X
Y = labeled.iloc[:,0].values
X = labeled.iloc[:,1:].values
#need to reshape the Y values
Y = Y.reshape(-1,1)
print(X)

[[  2011    190 125000 ...      1      1      3]
 [  2004    163 125000 ...     14      1      8]
 [  2001     75 150000 ...     38      7      7]
 ...
 [  1996    102 150000 ...     38      1      0]
 [  2002    100 150000 ...     38      1      1]
 [  2013    320  50000 ...      2      7      4]]


In [71]:
Y

array([[18300],
       [ 9800],
       [ 1500],
       ...,
       [ 9200],
       [ 3400],
       [28990]])

In [72]:
from sklearn.model_selection import cross_val_score, train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state = 3)
print(X_train)
print(X_test)
print(Y_train)
print(Y_test)

[[  2002    116 150000 ...     10      1      1]
 [  1999    193 150000 ...     20      7      2]
 [  2011    105  50000 ...     38      1      4]
 ...
 [  1994    102 150000 ...      2      7      4]
 [  1995     60 150000 ...     24      7      7]
 [  2012    313  50000 ...      1      1      1]]
[[  2008    140 150000 ...      1      1      4]
 [  2000     60 150000 ...     38      7      7]
 [  2004     54 125000 ...     38      7      7]
 ...
 [  2001    102 150000 ...     20      7      4]
 [  2003    146 150000 ...      2      7      2]
 [  1999     75 150000 ...     24      7      7]]
[[ 1500]
 [ 5700]
 [13000]
 ...
 [  800]
 [  800]
 [50000]]
[[10000]
 [ 1500]
 [ 2699]
 ...
 [ 1300]
 [ 5000]
 [  777]]


In [73]:
#Model building and Fitting
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score
regressor = RandomForestRegressor(n_estimators=1000, max_depth=10, random_state=34)
print(regressor)


RandomForestRegressor(max_depth=10, n_estimators=1000, random_state=34)


In [74]:
#fitting the model
regressor.fit(X_train, np.ravel(Y_train,order='C'))
print(X_train)
print(Y_train)


[[  2002    116 150000 ...     10      1      1]
 [  1999    193 150000 ...     20      7      2]
 [  2011    105  50000 ...     38      1      4]
 ...
 [  1994    102 150000 ...      2      7      4]
 [  1995     60 150000 ...     24      7      7]
 [  2012    313  50000 ...      1      1      1]]
[[ 1500]
 [ 5700]
 [13000]
 ...
 [  800]
 [  800]
 [50000]]


In [75]:
#predicting the values fo test test
y_pred = regressor.predict(X_test)
#printing the Accuraccy for test set
print(r2_score (Y_test,y_pred))

0.834527626497731


In [78]:
#saving the model for future use. 
filename = 'resale_model.sav' 
pickle.dump(regressor, open(filename, 'wb'))